/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import sorteo.participantes;

/**
 *
 * @author pedro
 */
public class Principal extends javax.swing.JFrame {

  public ArrayList<participantes> participantes=new ArrayList<participantes>();
  public ArrayList<participantes> ganadores=new ArrayList<participantes>();
  public int ganadorTotal;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        participantes p1= new participantes();
        p1.Nombre="Participante 1";
        p1.imagen= new ImageIcon(getClass().getResource("../participantes/p1.jpg"));
        participantes p2= new participantes();
        p2.Nombre="Participante 2";
        p2.imagen= new ImageIcon(getClass().getResource("../participantes/p2.jpg"));
        participantes p3= new participantes();
        p3.Nombre="Participante 3";
        p3.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
        participantes p4= new participantes();
        p4.Nombre="Participante 4";
        p4.imagen= new ImageIcon(getClass().getResource("../participantes/p1.jpg"));
        
        participantes p5= new participantes();
        p5.Nombre="Participante 5";
        p5.imagen= new ImageIcon(getClass().getResource("../participantes/p2.jpg"));
        
        participantes p6= new participantes();
        p6.Nombre="Participante 6";
        p6.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
        participantes p7= new participantes();
        p7.Nombre="Participante 7";
        p7.imagen= new ImageIcon(getClass().getResource("../participantes/p2.jpg"));
        
        participantes p8= new participantes();
        p8.Nombre="Participante 8";
        p8.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
        participantes p9= new participantes();
        p9.Nombre="Participante 9";
        p9.imagen= new ImageIcon(getClass().getResource("../participantes/p2.jpg"));
        
        participantes p10= new participantes();
        p10.Nombre="Participante 10";
        p10.imagen= new ImageIcon(getClass().getResource("../participantes/p2.jpg"));
        
        participantes p11= new participantes();
        p11.Nombre="Participante 11";
        p11.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
        participantes p12= new participantes();
        p12.Nombre="Participante 12";
        p12.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
        participantes p13= new participantes();
        p13.Nombre="Participante 13";
        p13.imagen= new ImageIcon(getClass().getResource("../participantes/p3.jpg"));
        
      participantes.add(p1);
      participantes.add(p2);
      participantes.add(p3);
      participantes.add(p4);
      participantes.add(p5);
      participantes.add(p6);
      participantes.add(p7);
      participantes.add(p8);
      participantes.add(p9);
      participantes.add(p10);
      participantes.add(p11);
      participantes.add(p12);
      participantes.add(p13);
      String nombresXD="<html> <body> ";
      
      for (int i=0; i<this.participantes.size(); i++){
          String actual=this.participantes.get(i).Nombre;
          nombresXD=nombresXD+ (i+1)+" - "+actual +"<br>";
    
    }
      nombresXD=nombresXD+ "</body> </html>";
     this.lblParticipantes.setText(nombresXD); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGanador = new javax.swing.JButton();
        lblFelicidades = new javax.swing.JLabel();
        lblParticipantes = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();
        lblMsjGanador = new javax.swing.JLabel();
        lblGanadoresLista = new javax.swing.JLabel();
        lblFotoParticipante = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 25)); // NOI18N
        jLabel1.setText("Paquetes FREE!!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 23, 239, 43));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("PARTICIPANTES:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 115, -1, -1));

        btnGanador.setText("SELECCIONAR GANADOR");
        btnGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 43));

        lblFelicidades.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        getContentPane().add(lblFelicidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 210, 38));

        lblParticipantes.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        lblParticipantes.setText("Ninguno xD");
        getContentPane().add(lblParticipantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 173, 460));

        lblGanador.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(lblGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 20));

        lblMsjGanador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMsjGanador.setText("Seleccionados");
        getContentPane().add(lblMsjGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, -1, -1));

        lblGanadoresLista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lblGanadoresLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 171, 140, 370));

        lblFotoParticipante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFotoParticipante.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(lblFotoParticipante, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 260, 260));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/participantes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanadorActionPerformed
       ganadorTotal+=1;
     //   if (ganadorTotal<4){
        int maximo= this.participantes.size();
        int ganador = (int) (Math.random() * maximo);
        String nombreG= this.participantes.get(ganador).Nombre;
        ImageIcon fotoG=this.participantes.get(ganador).imagen;
        this.lblGanador.setText(nombreG);
        this.lblFotoParticipante.setIcon(this.participantes.get(ganador).imagen);
        this.lblFelicidades.setText("FELICIDADES!!!");
        this.ganadores.add(this.participantes.get(ganador));
        this.participantes.remove(ganador);
        
    //    }
        
        
        String nombresXD="<html> <body> ";
      for (int i=0; i<this.ganadores.size(); i++){
          String actual=this.ganadores.get(i).Nombre;
          nombresXD=nombresXD+ (i+1)+" - "+actual +"<br>";
    
    }
      nombresXD=nombresXD+ "</body> </html>";
     this.lblGanadoresLista.setText(nombresXD); 
     
     if (ganadorTotal==3){
     ganadores form2= new ganadores(this.ganadores);
     form2.show();
     }
     
     if (ganadorTotal==6){
     ganadores form2= new ganadores(this.ganadores);
     form2.show();
     }
     
    }//GEN-LAST:event_btnGanadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGanador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFelicidades;
    private javax.swing.JLabel lblFotoParticipante;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblGanadoresLista;
    private javax.swing.JLabel lblMsjGanador;
    private javax.swing.JLabel lblParticipantes;
    // End of variables declaration//GEN-END:variables
}
